### PR TITLE
Basic training

### PR DESCRIPTION
**Pull request by enochtsang**
@bill-luu 

This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/recruit-resources/14)

### CODE REVIEW

**Comment by bill-luu** [comment]
Gordon could you take another look at this? Try out the new functions I made in `main`, and let me know if you think I should implement more functions.

Once you give it the Ok, Enoch can take a look and has merge rights.

**Comment by cheunggg** [comment]
Looks good! Good uses of dereference operators, address of operators, and references.

I would suggest moving the Person stuff in main.cpp to a different function, and call that function in main(), but that function call should be originally commented out. I think myswap and myincrement is a good intro to pointers and references, it would be nice for the recruits to do these first and test it out before moving on to Person.

Also delete(Joe); should be included before the return(0); in main.cpp, otherwise there is a memory leak. In the destructor of Person, age_ (assuming it was dynamically allocated) should also be deleted (but that's the recruits job)

**Comment by enochtsang** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/BasicRecruitTraining.cbp, line 24 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq8qqN_ulY3tQVPPug:-KSq8qqN_ulY3tQVPPuh:b-xezscr) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/BasicRecruitTraining.cbp#L24)):*
> ```
> 				<Option compiler="gcc" />
> 				<Compiler>
> 					<Add option="-O2" />
> ```

We should the compiler flag to treat warnings as errors, `-Werror`

---

*[Basic-Recruit-Training/BasicRecruitTraining.depend, line 1 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq8xcVe_TTzZA3TuAH:-KSq8xcVe_TTzZA3TuAI:bvt4xxb) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/BasicRecruitTraining.depend#L1)):*
> ```
> # depslib dependency file v1.0
> ```

This file should be deleted, I think this is person specific, add *.depend to the `.gitignore`.

---

*[Basic-Recruit-Training/main.cpp, line 1 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqA50aCWB3hn35goHU:-KSqA50aCWB3hn35goHV:b-8q8d0o) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L1)):*
> ```cpp
> #include <iostream> //Imports cout
> ```

Please run these source files through astyle.

---

*[Basic-Recruit-Training/main.cpp, line 12 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9O2JWYudGRdQRL4K:-KSq9O2KqdcZtiiQH6kd:bz2fis4) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L12)):*
> ```cpp
>         std::cout << "Incorrect." << std::endl;
>         std::cout << "Expected: " << correctAnswer << std::endl;
>         std::cout << "You got: " << myAnswer << std::endl;
> ```

These can use one std::cout call.
```
        std::cout << "Incorrect." << std::endl
                  << "Expected: " << correctAnswer << std::endl
                  << "You got: " << myAnswer << std::endl;
```

---

*[Basic-Recruit-Training/main.cpp, line 23 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAMlLiYukxTFB-wO6:-KSqAMlLiYukxTFB-wO7:bb76mu4) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L23)):*
> ```cpp
> {
> }
> //Using y++ or similar variants is not allowed for this function.
> ```

Why?

---

*[Basic-Recruit-Training/main.cpp, line 33 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAYzW1RkDlxjj9O5B:-KSqAYzW1RkDlxjj9O5C:b-sr8gq) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L33)):*
> ```cpp
>     int b = 6;
>     int* c = 0;
>     //Implement mySwap() on a & b.
> ```

`Implement` is pretty weird here. I would use `pass in a and b into mySwap()`

---

*[Basic-Recruit-Training/main.cpp, line 35 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAfq-wBqdkooDpEcY:-KSqAfq-wBqdkooDpEcZ:b-85ik2u) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L35)):*
> ```cpp
>     //Implement mySwap() on a & b.
> 
>     //Implement myIncrement() to Increment a.
> ```

Same here, use `pass in`

---

*[Basic-Recruit-Training/main.cpp, line 51 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAmLP6K86e25qjRD7:-KSqAmLP6K86e25qjRD8:bcd5hta) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L51)):*
> ```cpp
>     Person Bob("Bob", 30);
>     Bob.printInfo();
>     Person* Joe = new Person("Joe", 15);
> ```

Let's separate Bill, Bob, and Joe all by one line.

---

*[Basic-Recruit-Training/main.cpp, line 70 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBBt_xWd4lVBh9nBC:-KSqBBt_xWd4lVBh9nBD:b-xdn48o) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L70)):*
> ```cpp
> 
>     std::cout << "Checking Person::Birthday:" << std::endl;
>     std::cout << myBirthdayAnswer.str() << std::endl;
> ```

Use on `cout` call.

---

*[Basic-Recruit-Training/Person.h, line 1 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBw_Ld1hKeDWbL-j2:-KSqBw_Ld1hKeDWbL-j3:b32thjp) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L1)):*
> ```objc
> //This line is a preprocessor directive that prevents this header file from accidentally being included multiple times by source files.
> ```

The wording here is off. `accidentally` is weird because it is very common to include a header multiple times across various source files. I would say the real purpose of include guards is to prevent the file from being compiled multiple times. If new recruits want more reasoning they can ask us ourselves, we can just say `#pragma once` prevents the header from being compiled multiple times. Maybe also state every header should have it.

---

*[Basic-Recruit-Training/Person.h, line 8 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBPH56ZU_wvuwQtC4:-KSqBPH56ZU_wvuwQtC5:b5e3uz1) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L8)):*
> ```objc
> {
> public:
> //A Rule of Thumb when designing classes is to have a default constructor, regular constructor, and a destructor.
> ```

A space after a `//` look much better.

---

*[Basic-Recruit-Training/Person.h, line 10 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBbg2aIIosLn310vP:-KSqBbg2aIIosLn310vQ:b-wb1xx0) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L10)):*
> ```objc
> //A Rule of Thumb when designing classes is to have a default constructor, regular constructor, and a destructor.
> 	Person();
> 	Person(const std::string name, int age);
> ```

This should be a const reference.

---

*[Basic-Recruit-Training/Person.h, line 14 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBgf4H7G1J7mW33VN:-KSqBgf4H7G1J7mW33VO:bs5wt8f) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L14)):*
> ```objc
> 
> 	int getAge() const;
> 	std::string getName() const;
> ```

This should return a const reference.

---

*[Basic-Recruit-Training/Person.h, line 18 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBZ1-p7C8nFgqMLUW:-KSqBZ1-p7C8nFgqMLUX:b-pm06rv) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L18)):*
> ```objc
> 	void printInfo();
> 
> 	void setName(const std::string newName);
> ```

This should be passed in as a const reference.

---

*[Basic-Recruit-Training/Person.h, line 20 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBV9FxY05_PVRjsDo:-KSqBV9FxY05_PVRjsDp:b-wx4bf9) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L20)):*
> ```objc
> 	void setName(const std::string newName);
> 	void setAge(int newAge);
> //Print the combined Age of everyone pointed to by x
> ```

Put function comments beside the function not above.

---

*[Basic-Recruit-Training/Person.h, line 25 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBoOS0SviVY1yL5BQ:-KSqBoOS0SviVY1yL5BR:bex3wqa) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L25)):*
> ```objc
> private:
> 	std::string name_;
> //age_ should be a dynamically allocated.
> ```

Short comments like this are better beside than above.

---

*[Basic-Recruit-Training/README.md, line 4 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9hSJSGpbN4Ndse_F:-KSq9hSJSGpbN4Ndse_G:bi0m7hs) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/README.md#L4)):*
> ```Markdown
> 
> This Exercise is designed to introduce you to the concepts of pointers, references, functions, and class creation in C++.
> In this exercise, you will have to create the Person.cpp file and implement the definition of all of the functions within Person.h. In addition, you must complete the definitions of `mySwap()` and `myIncrement()` and implement them in `main`. The program will verify that you have correctly completed the exercise.
> ```

write this README in asciidoc please.

---

*[Basic-Recruit-Training/README.md, line 6 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9wZhb9oYnUXrtGUw:-KSq9wZhb9oYnUXrtGUx:b-cyewbb) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/README.md#L6)):*
> ```Markdown
> In this exercise, you will have to create the Person.cpp file and implement the definition of all of the functions within Person.h. In addition, you must complete the definitions of `mySwap()` and `myIncrement()` and implement them in `main`. The program will verify that you have correctly completed the exercise.
> 
> This project was designed for the Code::Blocks IDE, download here from www.codeblocks.org. Codeblocks requires a compiler, you can download the GNU GCC compiler from https://sourceforge.net/projects/tdm-gcc/?source=typ_redirect
> ```

Codeblocks installation should come with a compiler no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/main.cpp, line 23 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAMlLiYukxTFB-wO6:-KSqa8vQIeXTuIpwetUg:btqw092) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L23)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> Why?
</details>
Actually I could have worded that better haha
I was trying to say that they needed to deference the pointer, and that they can't just change the header to be `int x` and go from there. I'll change it to clariy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/main.cpp, line 23 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAMlLiYukxTFB-wO6:-KSqhCCSTrEg9vy0z-4T:bquzvui) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L23)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Actually I could have worded that better haha
> I was trying to say that they needed to deference the pointer, and that they can't just change the header to be `int x` and go from there. I'll change it to clariy
</details>
// Blocking comment for reviewable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/main.cpp, line 12 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9O2JWYudGRdQRL4K:-KStG5j9PXC_pW0o-pFL:bb6un1j) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L12)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> These can use one std::cout call.
> ```
>         std::cout << "Incorrect." << std::endl
>                   << "Expected: " << correctAnswer << std::endl
>                   << "You got: " << myAnswer << std::endl;
> ```
> 
</details>
Done

---

*[Basic-Recruit-Training/main.cpp, line 23 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqAMlLiYukxTFB-wO6:-KStJRB_FmAmmeMKZbMf:blq389a) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/main.cpp#L23)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> // Blocking comment for reviewable
</details>
I'll make a note in the README to explicitly state that they must follow headers & function definitions

---

*[Basic-Recruit-Training/README.md, line 6 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9wZhb9oYnUXrtGUw:-KStWfw3WTftI5iJapho:b-aal2d4) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/README.md#L6)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> Codeblocks installation should come with a compiler no?
</details>
The installation on my surface required me to select from a list of compilers whose names were all grayed out, requiring me to download the GNU GCC compiler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/README.md, line 6 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9wZhb9oYnUXrtGUw:-KStdVpYz50wavneYoTw:b-n2ekwh) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/README.md#L6)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> The installation on my surface required me to select from a list of compilers whose names were all grayed out, requiring me to download the GNU GCC compiler.
</details>
Was it hard at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/README.md, line 6 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq9wZhb9oYnUXrtGUw:-KStfOni62mrwYl93GiB:bfq42gm) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/README.md#L6)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> Was it hard at all?
</details>
iirc My installation was fine, but I think Gordon had some issues with it that he mentioned in previous comments (Back in the old repo)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Review status: 3 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/BasicRecruitTraining.cbp, line 24 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq8qqN_ulY3tQVPPug:-KSx01pjxLiWe4IsikJh:bo8mx32) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/BasicRecruitTraining.cbp#L24)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> We should the compiler flag to treat warnings as errors, `-Werror`
</details>
Each compiler has different options, I'll need to install the mingw compiler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[Basic-Recruit-Training/BasicRecruitTraining.cbp, line 24 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq8qqN_ulY3tQVPPug:-KSxH7BNZJf4sxt9lvr1:b3sy3u0) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/BasicRecruitTraining.cbp#L24)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Each compiler has different options, I'll need to install the mingw compiler.
</details>
Installed it, apparently it's not an option?


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Reviewed 1 of 4 files at r3, 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[Basic-Recruit-Training/BasicRecruitTraining.cbp, line 24 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSq8qqN_ulY3tQVPPug:-KSyyXyfuM4-ruTma_uc:b-hf6ezz) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/BasicRecruitTraining.cbp#L24)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Installed it, apparently it's not an option?
> 
> 
</details>
-Werror is definietly available, but is not given in that list. The number of compiler options is actually insane and not all listed there. In the other compiler options, put -Werror.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Reviewed 1 of 4 files at r3, 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Basic-Recruit-Training/Person.h, line 1 at r2](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KSqBw_Ld1hKeDWbL-j2:-KSyziU1GUFmwiSCLvEl:b-1ngku0) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/ae2abb5ad74ebf51bc9e3150bc7bedabe73b3138/Basic-Recruit-Training/Person.h#L1)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> The wording here is off. `accidentally` is weird because it is very common to include a header multiple times across various source files. I would say the real purpose of include guards is to prevent the file from being compiled multiple times. If new recruits want more reasoning they can ask us ourselves, we can just say `#pragma once` prevents the header from being compiled multiple times. Maybe also state every header should have it.
</details>
"compiled multiple times by source files" is still weird. I get what you're saying, but a compiler compiles files, not source files haha. In general, it's also bad to have such long lines. A good rule of thumb is a new line for every sentence. I would put

```c++
// #pragma once ensures this header is only compiled once.
// Every header file should have this line at the top.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Basic-Recruit-Training/BasicRecruitTraining.layout, line 12 at r5](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14#-KT1E6uHvfoYloFet_5p:-KT1E6uHvfoYloFet_5q:bqvaqwo) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/6de148bb8aa92760c2c96f20cfbb9dd7c3abe40c/Basic-Recruit-Training/BasicRecruitTraining.layout#L12)):*
> ```
> 	<File name="main.cpp" open="1" top="1" tabpos="1" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
> 		<Cursor>
> 			<Cursor1 position="1880" topLine="47" />
> ```

I think this file should be ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by enochtsang** [comment]
Reviewed 3 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Comment by bill-luu** [comment]
Reviewed 2 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/14)*

**Pull request merged**
