### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by enochtsang**
@bill-luu

---

This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/recruit-resources/15)

### CODE REVIEW

**Comment by enochtsang** [comment]
Still deal with the comments in the old PR https://github.com/UCSolarCarTeam/UCSolarTeam-Setup-Script/pull/1

**Comment by bill-luu** [comment]
Updated comments for `UCSolarTeamInit.sh` & `README.md`, still have to address the comments on the other ones. Should I make a new .travis file?

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[SetupScript/LinuxMintInstallScript.sh, line 88 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/15#-KTqZV9aohUrWSB5f3JY:-KTqZV9aohUrWSB5f3JZ:b-ykpthu) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/5ae9dab0ac41f9867e386338fd337ee2dbcdca4c/SetupScript/LinuxMintInstallScript.sh#L88)):*
> ```Shell
> sudo tar -xzvf jdk-8u101-linux-x64.tar.gz
> sudo mv jdk1.8.0_101/ /opt/
> ```

Before you said to install Java through the package manager, to clarify you mean the official Java Package manager right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/15#-:-KTqZhc4lqRL31zqC7k3:bcmftp1)*

**Comment by bill-luu** [comment]
Reviewed 2 of 13 files at r1, 3 of 11 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/15)*

**Comment by enochtsang** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SetupScript/UCSolarTeamInit.sh, line 88 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/15#-KTqZV9aohUrWSB5f3JY:-KU6A1OtTKSSYj_bMhQG:bmvkda0) ([raw file](https://github.com/ucsolarcarteam/recruit-resources/blob/5ae9dab0ac41f9867e386338fd337ee2dbcdca4c/SetupScript/UCSolarTeamInit.sh#L88)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> Before you said to install Java through the package manager, to clarify you mean the official Java Package manager right?
</details>
Uh, through apt-get?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/15)*

**Comment by enochtsang** [comment]
Squash your commits

**Comment by bill-luu** [comment]
This should now work on a Linux VM - all of the checks in UCSolarTeamInitTest.sh except for the Epsilon-Onboard-Media-Control and Epsilon Hermes will pass (I think we should wait until those repos are more stable before going with it). 

However, when `UCSolarTeamInitTest.sh` is run on Travis, there are still some errors that exist. Enoch can you help me out figure out why?

**Comment by enochtsang** [comment]
There's a whole bunch of extraneous commits in here, can you remove them?

**Comment by enochtsang** [comment]
Alright if you say it works, looks good to merge. @bill-luu can you make a new task to look into why the travis build errors.

**Pull request merged**
