### PR TITLE
Added some better function descriptions

### PR DESCRIPTION
**Pull request by bill-luu**
This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/recruit-resources/17)

### CODE REVIEW

**Comment by enochtsang** [comment]
LGTM

**Comment by cheunggg** [comment]
I would instead of saying " Increment the value at the address pointed to x by one, just say "increment value by 1".

Also personFunctions() in main should also be commented out

**Comment by enochtsang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/17#-:-KTgZ7pjuld0USClHzDs:bnfp4nl)*

**Comment by cheunggg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/17)*

**Comment by bill-luu** [comment]
I feel like they would try and increment the pointer, instead of the number, but yeah the wording is a bit off

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/17#-:-KTh0cCMKt12M8TtBQoV:b26mqmi)*

**Comment by cheunggg** [comment]
True, change the wording a bit and don't forget to comment out the entire void PersonFunction() block, otherwise the compiler will complain, the recruits should then comment out the entire block and the function call in main()

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/17#-:-KTh2OQV2Eg4yHE4ONiv:b9mfxr9)*

**Comment by bill-luu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/recruit-resources/17)*

**Pull request merged**
